### ISSUE TITLE
spec for ExAws.S3.upload/4 does not account for pass through options

### ISSUE THREAD

**Issue by tmaszk** [ex-aws/ex_aws_s3#122]
### Environment

* Elixir 1.12.0, Eralng OTP 24
* ExAws version 2.2.0

### Current behavior

Specifying upload pass through options, such as `content_type:`, to S3.upload/4 function causes the dialyzer to fail.

The documentation states that options such as `content_type` will be passed through, [see here](https://github.com/ex-aws/ex_aws_s3/blob/ed708adfd234624d28c6cb5e1688108e6b4b2275/lib/ex_aws/s3.ex#L705-L713).

But the forth argument in the [spec](https://github.com/ex-aws/ex_aws_s3/blob/ed708adfd234624d28c6cb5e1688108e6b4b2275/lib/ex_aws/s3.ex#L716-L721), only allows `opts :: upload_opts` which is defined [here](https://github.com/ex-aws/ex_aws_s3/blob/ed708adfd234624d28c6cb5e1688108e6b4b2275/lib/ex_aws/s3.ex#L685-L686) and doesn't allow for the pass through options.

I made a [simple project](https://github.com/tmaszk/update_option_problem), that demonstrates the problem on [this line](https://github.com/tmaszk/update_option_problem/blob/02ad6c950e2714a891bf89582e50068454b5c1e9/lib/update_option_problem.ex#L27).  You can run the dialyzer on the project to reproduce the problem.

### Expected behavior

The spec for the S3.upload/4 function should allow the pass through options, such as `content_type:`.

**Comment by bernardd** [comment]
This should already be resolved by https://github.com/ex-aws/ex_aws_s3/pull/120 - please let me know if it isn't.
