### ISSUE TITLE
`presigned_url` does not sign headers

### ISSUE THREAD

**Issue by NathanielScottStevens** [ex-aws/ex_aws_s3#124]
### Environment

* Elixir & Erlang versions (elixir --version): Elixir 1.10.3 & Erlang/OTP 22
* ExAws version `mix deps |grep ex_aws`
  * ex_aws 2.2.3 
  * ex_aws_lambda 2.0.2 
  * ex_aws_s3 2.3.0 
* HTTP client version. IE for hackney do `mix deps | grep hackney`:  1.17.4

### Current behavior
`S3.presigned_url(ExAws.Config.new(:s3), :get, "bucket", "path/to/file", headers: [{"response-content-disposition", "attachment;filename.pdf"}])`

`presigned_url` successfully returns a url, however, upon using it, aws returns a `SignatureDoesNotMatch` error:
```
...
<Code>SignatureDoesNotMatch</Code>
<Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message>
...
<CanonicalRequest>GET /path/to/file X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=[REDACTED]&X-Amz-Expires=3600&X-Amz-Security-Token=[REDACTED]&X-Amz-SignedHeaders=host%3Bresponse-content-disposition host:s3.amazonaws.com response-content-disposition: host;response-content-disposition UNSIGNED-PAYLOAD</CanonicalRequest>
...
```

### Expected behavior
The presigned url should be accepted by aws.

### Notes
It appears this issue occurs with any headers provided. Without the headers, it works beautifully.

**Comment by trbngr** [comment]
I was running into the same issue and I also thought it was a defect. It's not. The headers *are* being signed.  In order to use the URL, you have to pass the headers that you signed with the request with the resulting URL.

In my case, I'm using `fetch`.

So my backend is returning a presigned_url with my header signed.

``` elixir
  def handle_dispatch(command, opts) do
    headers = headers(command)

    with {:ok, url} <- sign(command, opts),
         {:ok, photo_id} <- add_photo(url) do
      %{id: photo_id, url: url, headers: Enum.into(headers, %{})}
    end
  end

  defp sign(%{bucket: bucket, key: key} = command, opts) do
    expires_in = Keyword.fetch!(opts, :expires_in)

    :s3
    |> ExAws.Config.new()
    |> ExAws.S3.presigned_url(:put, bucket, key,
      virtual_host: true,
      query_params: query_params(command),
      headers: headers(command),
      expires_in: expires_in
    )
  end

  defp query_params(_command) do
    [
      {"x-amz-acl", "public-read"}
    ]
  end

  defp headers(%{filename: filename}) do
    [
      {"Content-Disposition", ~s[inline; filename="#{filename}"]}
    ]
  end
```

and on the client:

``` javascript
import React from 'react';
import graphql from 'babel-plugin-relay/macro';

import { FilePicker } from '..';
import { useMutation } from 'react-relay';

const CREATE_UPLOAD_URL = graphql`
  mutation PhotoUploaderCreateUploadableMutation($name: String!) {
    upload: createUploadable(filename: $name) {
      id
      url
      headers
    }
  }
`;

export default function PhotoUploader({ onUpload }) {
  const [createUrl, loading] = useMutation(CREATE_UPLOAD_URL);

  const uploadFile = file => {
    createUrl({
      variables: { name: file.name },
      onCompleted: async ({ upload: { id, url, headers } }) => {

PASSING HEADERS TO FETCH IS THE KEY TO MAKING THIS WORK

        await fetch(url, {
          method: 'PUT',
          headers,
          body: file,
          mode: 'cors'
        });

        onUpload && onUpload(id);
      }
    });
  };

  return (
    <div>
      <FilePicker onChange={uploadFile} loading={loading} />
    </div>
  );
}
```

I hope this helps! 

Cheers 🍻

**Comment by trbngr** [comment]
In your case, because you're signing a `get` URL, you should probably use `query_params` instead of `headers`.

**Comment by NathanielScottStevens** [comment]
Thank you @trbngr! This is really helpful, I appreciate you taking the time to lay it all out for me! 

In your second comment, are you saying that "Content-Disposition" can be provided as a query param instead of as a header (In which case, I assume the client does not need to add "Content-Disposition" to the request in the way necessitated by using a header)?

**Comment by trbngr** [comment]
I don't think that there is anything wrong in the docs. The reader just needs to understand the purpose of a presigned url and how it is meant to be used.

It's basically a contract between the signer and AWS. 

If you sign a url with headers, they are expected to be present, exactly, in the request that uses the signed url. Same with query parameters and anything else you use when signing.
