### ISSUE TITLE
ExAws.S3.upload/4 is missing type spec for `:timeout` option.

### ISSUE THREAD

**Issue by mattpolzin** [ex-aws/ex_aws_s3#127]
* Do not use the issues tracker for help or support (try Elixir Forum, Slack, IRC, etc.)
* Questions about how to contribute are fine.

### Environment

* Elixir & Erlang versions (elixir --version): Elixir 1.12 / Erlang 24.0
* ExAws version `mix deps |grep ex_aws`: 2.2.3
* HTTP client version. IE for hackney do `mix deps | grep hackney`: hackney 1.17.4

### Current behavior

Dialyzer failure with call to `ExAws.S3.upload/4` because `:timeout` option is not specified in the typespecs.

### Expected behavior

`:timeout` option, which is described in codedoc for `upload/4` should be specified in the typespecs for that function.

**Comment by bernardd** [comment]
Fixed - thanks @mattpolzin.
