### ISSUE TITLE
"The AWS Access Key Id you provided does not exist in our records" when listing objects in bucket

### ISSUE THREAD

**Issue by hebbo** [ex-aws/ex_aws_s3#13]
### Environment

Erlang/OTP 20 [erts-9.2.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.6.1 (compiled with OTP 20)

ex_aws_s3 v2.0.0

### Current behavior

I am getting an unexpected error from AWS when trying to do a simple list operation on a bucket:

```
iex(2)> ExAws.S3.list_objects("my-bucket") |> ExAws.request!(region: "us-west-2")
** (UndefinedFunctionError) function Poison.decode/1 is undefined (module Poison is not available)
    Poison.decode("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>InvalidAccessKeyId</Code><Message>The AWS Access Key Id you provided does not exist in our records.</Message><AWSAccessKeyId>REMOVED</AWSAccessKeyId><RequestId>REMOVED</RequestId><HostId>REMOVED</HostId></Error>")
    (ex_aws) lib/ex_aws/request.ex:58: ExAws.Request.client_error/2
    (ex_aws) lib/ex_aws/request.ex:42: ExAws.Request.request_and_retry/7
    (ex_aws) lib/ex_aws/operation/s3.ex:40: ExAws.Operation.ExAws.Operation.S3.perform/2
    (ex_aws) lib/ex_aws.ex:61: ExAws.request!/2
```

When I use the AWS cli on the same terminal session (AWS session set through env variables with aws-vault) I can list the objects without any issues. 

```
aws s3 ls s3://my-bucket --region us-west-2
```

Am I missing anything? Seems like the ex_aws_s3 is performing the request with unexpected parameters. Any ideas on what I am missing?

Thanks!

**Comment by hebbo** [comment]
Just to add up, I can successfully run this from my IEX console:

```
iex(16)> System.cmd("aws", ["s3", "ls", "s3://my-bucket", "--region", "us-west-2"])
{"2018-02-23 14:06:19          6 test.txt\n2018-02-23 15:16:35          6 test2.txt\n2018-02-23 17:30:36          6 test3.txt\n",
 0}
```

**Comment by benwilson512** [comment]
Can you show your ExAws config?

**Comment by ashokdudhade-cbs** [comment]
I ran into similar issue, adding security token in config fixed it. By default library adds  access_key_id and secret_access_key in configurations but not security token.
```
config :ex_aws,
  security_token: [{:system, "AWS_SECURITY_TOKEN"}, :instance_role]
```
