### ISSUE TITLE
Enhancement: Swap argument order for put_object_copy/5

### ISSUE THREAD

**Issue by fireproofsocks** [ex-aws/ex_aws_s3#191]
The argument order for `put_object_copy/5`  is "dest, src" which may be confusing for those expecting the "src, dest" ordering used by various CLI tools, e.g. Bash's `cp` or even `awscli`'s `cp`.
Same applies for `upload_part_copy/5`

What's the reasoning behind the current argument order?

**Comment by bernardd** [comment]
> may be confusing for those expecting the "src, dest" ordering used by various CLI tools

Yeah, but it makes perfect sense for those familiar with x86 assembly ;)

More seriously, I have no idea why it's that way ("it was like that when I got here"). But it is, and there's code out there that now relies on that ordering. If I was writing it from scratch I might do it the other way around, but we're here now.
