### ISSUE TITLE
Allow lifecycle rules with transitions of 0 days

### ISSUE THREAD

**Issue by hidnasio** [ex-aws/ex_aws_s3#198]
Thanks for the library.

### Environment

* Elixir & Erlang versions (elixir --version):

```
Erlang/OTP 24 [erts-12.1.5] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1]

Elixir 1.13.0 (compiled with Erlang/OTP 24)
```

* ExAws version `mix deps |grep ex_aws`

`ex_aws 2.2.5`
`ex_aws_s3 2.3.1`

* HTTP client version. IE for hackney do `mix deps | grep hackney`

`hackney 1.18.1`

### Current behavior

I have the following lifecycle rule created in AWS console.

```
<Rule>
  <ID>some id</ID>
  <Prefix>foo/bar</Prefix>
  <Status>Enabled</Status>
  <Transition>
    <Days>0</Days>
    <StorageClass>GLACIER</StorageClass>
  </Transition>
  <Expiration>
    <Days>2</Days>
  </Expiration>
</Rule>
```

But when trying to write it to S3 using ex_aws_s3 I get the following error:

```
** (FunctionClauseError) no function clause matching in ExAws.S3.Utils.livecycle_trigger/2

    The following arguments were given to ExAws.S3.Utils.livecycle_trigger/2:

        # 1
        :transition

        # 2
        {:days, 0}

    (ex_aws_s3 2.3.1) lib/ex_aws/s3/utils.ex:224: ExAws.S3.Utils.livecycle_trigger/2
    (ex_aws_s3 2.3.1) lib/ex_aws/s3/utils.ex:211: anonymous fn/3 in ExAws.S3.Utils.build_lifecycle_rule/1
    (elixir 1.13.0) lib/enum.ex:2396: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ex_aws_s3 2.3.1) lib/ex_aws/s3/utils.ex:208: ExAws.S3.Utils.build_lifecycle_rule/1
    (elixir 1.13.0) lib/enum.ex:1593: Enum."-map/2-lists^map/1-0-"/2
    (ex_aws_s3 2.3.1) lib/ex_aws/s3.ex:390: ExAws.S3.put_bucket_lifecycle/2
```

The problem is that the library doesn't accept 0 days for transitions

https://github.com/ex-aws/ex_aws_s3/blob/cdc60d3d6a5fe8eee5fd2f8b6bc2edca6e87d532/lib/ex_aws/s3/utils.ex#L227-L230

### Expected behavior

The library accepts 0 days for transitions.

**Comment by hidnasio** [comment]
Let me know if you want me to create a PR to fix the issue.

**Comment by bernardd** [comment]
Hi @hidnasio - yeah, it looks like this is just a typo in the original implementation. Please feel free to open a PR to correct it.
Apologies for the delay getting to this.
