### ISSUE TITLE
S3.upload not returning what I'm expecting from the docs

### ISSUE THREAD

**Issue by jakep36** [ex-aws/ex_aws_s3#20]
* Do not use the issues tracker for help or support (try Elixir Forum, Slack, IRC, etc.)
* Questions about how to contribute are fine.

### Environment

* Elixir & Erlang versions (elixir --version):
Elixir 1.6.4
* ExAws version: ex_aws 2.0.2
* HTTP client version: hackney 1.12.1

### Current behavior
```
"path/to/big/file"
|> S3.Upload.stream_file
|> S3.upload("my-bucket", "path/on/s3")
|> ExAws.request! #=> %{body: "", headers: [], status_code: 200}
```

Include code samples, errors and stacktraces if appropriate.

### Expected behavior
```
"path/to/big/file"
|> S3.Upload.stream_file
|> S3.upload("my-bucket", "path/on/s3")
|> ExAws.request! #=> {:ok, :done}
```

**Comment by benwilson512** [comment]
Docs have been fixed.
