### ISSUE TITLE
MalformedXML for S3 upload, but only for empty file

### ISSUE THREAD

**Issue by balduncle** [ex-aws/ex_aws_s3#3]
**NOTE:** I am using the latest ex_aws and ex_aws_s3 from github, to get the 2.0 functionality.  If this is related to my problem and the code is a work in progress, feel free to close this ticket. 😄 

I am trying to upload a file with the following code.

```
"filename"
|> ExAws.S3.Upload.stream_file
|> ExAws.S3.upload("bucket-name", "test/filename")
|> ExAws.request(ExAws.Config.new(:s3, [region: "my-region"]))
```

In my small amount of testing so far, this works for files with content but fails if I try to upload an empty file (i.e. one I created with `touch`).

```
** (ExAws.Error) ExAws Request Error!

{:error, {:http_error, 400, %{body: "<Error><Code>MalformedXML</Code><Message>The XML you provided was not well-formed or did not validate against our published schema</Message><RequestId>...</RequestId><HostId>...</HostId></Error>", headers: [{"x-amz-request-id", "..."}, {"x-amz-id-2", "..."}, {"Content-Type", "application/xml"}, {"Transfer-Encoding", "chunked"}, {"Date", "Tue, 07 Nov 2017 20:20:55 GMT"}, {"Connection", "close"}, {"Server", "AmazonS3"}], status_code: 400}}}

    (ex_aws) lib/ex_aws.ex:46: ExAws.request!/2
```

Relevant deps versions in case this is important...

```
* sweet_xml (Hex package) (mix)
  locked at 0.6.5 (sweet_xml) dd9cde44
  the dependency build is outdated, please run "mix deps.compile"
* ex_aws (https://github.com/ex-aws/ex_aws) (mix)
  locked at 74c97c2
  the dependency build is outdated, please run "mix deps.compile"
* ex_aws_s3 (https://github.com/ex-aws/ex_aws_s3) (mix)
  locked at 1dfb158
```

Any ideas what might be going wrong?  I was wondering if possibly some unique AWS codes happened to have special chars in them or something, but I didn't notice anything beyond `/`, `+` and `=`.

**Comment by balduncle** [comment]
For what it's worth I confirmed this is in 1.1 as well and I'm working around it by checking for 0 byte files and not attempting to upload them, since I don't need empty files anyway.

**Comment by benwilson512** [comment]
Interesting, I'll take a look!

**Comment by jtomaszewski** [comment]
The issue is still appearing for 2.0.0 as well.

**Comment by benwilson512** [comment]
PR welcome.
