### ISSUE TITLE
Issue with Regions

### ISSUE THREAD

**Issue by epinault** [ex-aws/ex_aws_s3#34]
* Do not use the issues tracker for help or support (try Elixir Forum, Slack, IRC, etc.)
* Questions about how to contribute are fine.

### Environment

% elixir --version
Erlang/OTP 21 [erts-10.0.8] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]

Elixir 1.7.3 (compiled with Erlang/OTP 21)
% mix deps |grep ex_aws
* ex_aws 2.1.0 (Hex package) (mix)
  locked at 2.1.0 (ex_aws) b9265152
* ex_aws_s3 2.0.1 (Hex package) (mix)
  locked at 2.0.1 (ex_aws_s3) 9e09366e

% mix deps | grep hackney
* hackney 1.14.0 (Hex package) (rebar3)
  locked at 1.14.0 (hackney) 66e29e78

### Current behavior

So my default config is 
```
config :ex_aws,
  access_key_id: [{:system, "AWS_ACCESS_KEY_ID"}, {:awscli, "default", 30}, :instance_role],
  secret_access_key: [
    {:system, "AWS_SECRET_ACCESS_KEY"},
    {:awscli, "default", 30},
    :instance_role
  ],
  region: "us-west-2"
```

Trying to do other region I get some weird behavior?

```
ExAws.S3.list_objects("outreach-insights")  |> ExAws.request(region: "us-west-1") 

10:50:41.129 [warn]  ExAws: Received redirect, did you specify the correct region?
{:error, {:http_error, 301, "redirected"}}
```

```
ExAws.S3.put_object("outreach0-insights", "yo", "hello") |> ExAws.request(region: "us-west-1")
{:error,
 {:http_error, 400,
  %{
    body: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>AuthorizationHeaderMalformed</Code><Message>The authorization header is malformed; the region 'us-west-2' is wrong; expecting 'us-west-1'</Message><Region>us-west-1</Region><RequestId>ABB891594B7B1A67</RequestId><HostId>pW/8POxk5rVecmj/9rJuAJBhrY/g2NZjG6Hs+RVxoUU4f7XmkyETQuSMnAMrLcAom6T+jLQfdqA=</HostId></Error>",
    headers: [
      {"x-amz-request-id", "ABB891594B7B1A67"},
      {"x-amz-id-2",
       "pW/8POxk5rVecmj/9rJuAJBhrY/g2NZjG6Hs+RVxoUU4f7XmkyETQuSMnAMrLcAom6T+jLQfdqA="},
      {"Content-Type", "application/xml"},
      {"Transfer-Encoding", "chunked"},
      {"Date", "Thu, 20 Sep 2018 17:50:53 GMT"},
      {"Connection", "close"},
      {"Server", "AmazonS3"}
    ],
    status_code: 400
```

### Expected behavior

that it would list my bucket or put object to the region specified in the request? What am I missing?

**Comment by benwilson512** [comment]
> Do not use the issues tracker for help or support.

Please use the forums or slack for support, thanks.
