### ISSUE TITLE
max_keys does not work with list_objects |> stream 

### ISSUE THREAD

**Issue by parlays** [ex-aws/ex_aws_s3#35]
Not an important issue.  In the documentation there an example for **list_objects**:
`S3.list_objects("my-bucket", max_keys: 5, encoding_type: "url") |> ExAws.stream!`

https://hexdocs.pm/ex_aws_s3/ExAws.S3.html#list_objects/2

The **max_keys** option does not work for me when piped into a stream.  It works properly when using ExAws.request.

**Comment by benwilson512** [comment]
```
iex(7)> S3.list_objects("bucket", max_keys: 5) |> ExAws.stream! |> Enum.to_list

08:28:33.255 [debug] Request URL: "https://s3.amazonaws.com/bucket/?max-keys=5"
```
It looks like it works to me. The `max_keys` option is about how many keys to get in a single request. If you want to limit the number of results you get with stream you should use `Stream.take/2` or `Enum.take/2`

**Comment by parlays** [comment]
Gotcha!  I will enable debugging next time.  I thought stream was used to make a single lazy request, I didn't know it made multiple requests.  Thanks for the info.  Awesome library, thanks for making it!

**Comment by parlays** [comment]
I noticed that ExAws.Stream is not on the Hexdocs page:
https://hexdocs.pm/ex_aws/ExAws.html

**Comment by benwilson512** [comment]
It shouldn't. the `ExAws.Request` module probably shouldn't even be in the docs since it's an internal module. The two functions people actually use are both documented, here's the stream one: https://hexdocs.pm/ex_aws/ExAws.html#stream!/2
