### ISSUE TITLE
Support AWS S3 Accelerated Transfer

### ISSUE THREAD

**Issue by xdays** [ex-aws/ex_aws_s3#40]
### Environment

```
$ elixir -v
Erlang/OTP 21 [erts-10.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]

Elixir 1.7.3 (compiled with Erlang/OTP 21)

$ mix deps | grep "ex_aws\|hackney"
* hackney 1.14.3 (Hex package) (rebar3)
  locked at 1.14.3 (hackney) b5f6f5dc
* ex_aws 2.0.2 (Hex package) (mix)
  locked at 2.0.2 (ex_aws) 8df2f96f
* ex_aws_sns 2.0.0 (Hex package) (mix)
  locked at 2.0.0 (ex_aws_sns) c51dda8c
* ex_aws_firehose 2.0.0 (Hex package) (mix)
  locked at 2.0.0 (ex_aws_firehose) afb1b252
* ex_aws_s3 2.0.1 (Hex package) (mix)
  locked at 2.0.1 (ex_aws_s3) 9e09366e
* ex_aws_elastic_transcoder 2.0.0 (Hex package) (mix)
  locked at 2.0.0 (ex_aws_elastic_transcoder) d51ad7b7
```
### Current behavior

AWS S3 Accelerated Transfer is not supported

### Expected behavior

Refer: https://github.com/ex-aws/ex_aws/issues/418

**Comment by alvesl** [comment]
Hi! Any updates on this one? 👍

**Comment by alexandremcosta** [comment]
I would love to see this, or at least a roadmap to understand if this will be done in future

**Comment by benwilson512** [comment]
PR welcome.

**Comment by alexandremcosta** [comment]
I might do it. Two important questions:
- Is this on roadmap, or is anybody else working on this?
- Does ex_aws support virtual host?

**Comment by Tmw** [comment]
Hey guys, for everyone hitting the same _issue_ and until the PR #65 is merged, I worked around it by _manually_ overriding the `:host` field in the `ExAws.Config` map and passing `virtual_host: true` when signing the URL.

**Example**

```elixir
config = ExAws.Config.new(:s3) |> Map.put(:host, "s3-accelerate.amazonaws.com")
ExAws.S3.presigned_url(config, :put, "bucket", "object", virtual_host: true)
```
