### ISSUE TITLE
put_bucket_policy argument error

### ISSUE THREAD

**Issue by scsinke** [ex-aws/ex_aws_s3#41]
### Environment

* Elixir & Erlang versions (elixir --version)
`Elixir 1.7.4 (compiled with Erlang/OTP 21)`
* ExAws version `mix deps |grep ex_aws`
`ex_aws 2.1.0 (Hex package) (mix)`
* HTTP client version. IE for hackney do `mix deps | grep hackney` 
`hackney 1.12.1 (Hex package) (rebar3)`

### Current behavior

I believe that the map is not parsed to a string. Therefor the content-size cannot be calculated because it needs a string.

action: `ExAws.S3.put_bucket_policy("testing", %{"a" => "b"}) |> ExAws.request!`

result: ```** (ArgumentError) argument error
    :erlang.iolist_to_binary(%{"a" => "b"})
    (crypto) crypto.erl:368: :crypto.hash/2
    (ex_aws) lib/ex_aws/auth/utils.ex:20: ExAws.Auth.Utils.hash_sha256/1
    (ex_aws) lib/ex_aws/operation/s3.ex:31: ExAws.Operation.ExAws.Operation.S3.perform/2```

### Expected behavior

action: `ExAws.S3.put_bucket_policy("testing", %{"a" => "b"}) |> ExAws.request!`

This result is build by breaking contract and to supply a string instead of a map. 
`ExAws.S3.put_bucket_policy("testing", "testing") |> ExAws.request!`

result: ```{:error,
 {:http_error, 400,
  %{
    body: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>MalformedPolicy</Code><Message>Policy has invalid resource.</Message><Resource>/testing/</Resource><RequestId>1568816DC6089534</RequestId><HostId>3L137</HostId></Error>",
    headers: [
      {"Accept-Ranges", "bytes"},
      {"Content-Security-Policy", "block-all-mixed-content"},
      {"Content-Type", "application/xml"},
      {"Server", "Minio/RELEASE.2018-10-25T01-27-03Z (linux; amd64)"},
      {"Vary", "Origin"},
      {"X-Amz-Request-Id", "1568816DC6089534"},
      {"X-Xss-Protection", "1; mode=block"},
      {"Date", "Mon, 19 Nov 2018 10:59:40 GMT"},
      {"Transfer-Encoding", "chunked"}
    ],
    status_code: 400
  }}}```

**Comment by benwilson512** [comment]
Yeah I think the typespec is wrong. A map doesn't make a lot of sense for a policy anyway. I'd consider just pushing up a raw string policy for now and seeing if that works.

**Comment by scsinke** [comment]
Raw string is working fine
