### ISSUE TITLE
MatchErrors during upload are not handled, Task.async_stream terminates during upload_chunk  

### ISSUE THREAD

**Issue by gheorghina** [ex-aws/ex_aws_s3#51]
* Do not use the issues tracker for help or support (try Elixir Forum, Slack, IRC, etc.)
* Questions about how to contribute are fine.

### Environment

* Elixir & Erlang versions (elixir --version):
* Erlang/OTP 21
* Elixir (1.7.4)
* ExAws version mix deps |grep ex_aws: ex_aws_s3 2.0.1, ex_aws 2.0.2
* HTTP client version: machine-gun 0.1.5 

### Current behaviour

Errors in ExAws.S3.upload() cannot be handled in the parent processes. 
Failure examples for larger packages upload ( > 5MB )(these can be reproduced in the context of environments which can have high latency in uploading to AWS; these scenarios may work after a retry):

[error] Task #PID<0.2306.0> started from #PID<0.1758.0> terminating
** (ExAws.Error) ExAws Request Error!
{:error, {:http_error, 403, %{body: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message> 

### Expected behaviour
Handle internal tasks errors and return an {:error, :failed_to_upload} in ExAws.S3.Upload.complete

**Comment by bernardd** [comment]
Resolved by #53 / #116
