### ISSUE TITLE
Release of Download Stream functionality

### ISSUE THREAD

**Issue by LtChae** [ex-aws/ex_aws_s3#67]
My team is interested in using the recently added `ExAws.stream!()` functionality for `ExAws.S3.download_file`. For now we're pulling from this repo with a pinned commit, but we'd like to use a proper hex version if possible.

When do you expect to release this functionality?

If this is the wrong place to ask this kind of question, just let me know where I should. The submission guidelines didn't seem to cover this.

#60

**Comment by Lazarus404** [comment]
I'd like to use it, too.  Any idea when this release will happen?  Thanks

**Comment by LtChae** [comment]
6 month checkin: is there any plan to cut a new release of this?

**Comment by gabrielmancini** [comment]
+1

**Comment by bernardd** [comment]
Not sure what the +1 is for. Near as I can tell the feature has been in there since at least 2.1, released last year.
