### ISSUE TITLE
(FunctionClauseError) no function clause matching in :raw_file_io_raw.open_layer/3

### ISSUE THREAD

**Issue by houmanka** [ex-aws/ex_aws_s3#69]
When I am trying to upload to S3 I get:
`(FunctionClauseError) no function clause matching in :raw_file_io_raw.open_layer/3`

It used to work before I upgrade to OTP 22 and Elixir 1.9 though.

```
  defp deps do
    [
      {:ex_aws, "~> 2.0"},
      {:ex_aws_s3, "~> 2.0"},
      {:hackney, "~> 1.9"},
      {:sweet_xml, "~> 0.6"},
    ]
  end

```

Here is the code that do it:

```
cloud_s3.path
      |> S3.Upload.stream_file
      |> S3.upload(cloud_s3.s3_bucket, cloud_s3.s3_output)
      |> ExAws.request
      |> case do
        {:ok, result } ->
          Logger.warn "S3: Done for #{inspect(result)}"
        _ ->
          Logger.warn "S3: Err for #{inspect(cloud_s3)}, Not sure why!}"
      end
```

Now I logged `cloud_s3.path |> S3.Upload.stream_file` out and here is the result:

```
%File.Stream{
  line_or_bytes: 5242880,
  modes: [:raw, :raw, {:read_ahead, 65536}, :binary, :binary],
  path: "/var/folders/3m/n6p202494w15b5xx0fc15y580000gn/T//plug-1562/multipart-1562739090-118134755902720-4",
  raw: true
}
```

I think, `raw: true` this is the reason I get error. I am not sure how to fix it.

**Comment by stocks29** [comment]
I believe this issue is related to https://github.com/elixir-lang/elixir/issues/7771 and has been fixed in a more recent version of `ex_aws_s3`. Upgrading to 2.0.2 resolved the error for me. I think this can be closed.
