### ISSUE TITLE
x-amz-acl not signed in presigned_url

### ISSUE THREAD

**Issue by dfalling** [ex-aws/ex_aws_s3#73]
S3 requires `x-amz-acl` to be signed.  Without it, the request will 403.

I'm generating a presigned URL with this:
```elixir
    key = Ecto.UUID.generate()

    query_params = [{"x-amz-acl", "public-read"}]
    presign_options = [query_params: query_params]

    with {:ok, url} <-
           ExAws.Config.new(:s3)
           |> ExAws.S3.presigned_url(:put, @bucket, key, presign_options) do
      {:ok, %FileUpload{url: url, key: key}}
    end
```

### Environment

* Elixir 1.9.0 & Erlang 22
* ExAws 2.0.2
* Hackney 1.15.1

### Current behavior

The generated URL doesn't sign the `x-amz-acl` header:
```
https://s3.amazonaws.com/REDACTED?Content-Type=image%2Fpng&x-amz-acl=public-read&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=REDACTED%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20190820T212049Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Signature=REDACTED
```

Note the only signed headers are `host` and `X-Amz-Signature`.

```xml
<Error>
  <Code>AccessDenied</Code>
  <Message>There were headers present in the request which were not signed</Message>
  <HeadersNotSigned>x-amz-acl</HeadersNotSigned>
  <RequestId>REDACTED</RequestId><HostId>REDACTED</HostId>
</Error>
```

### Expected behavior

The generated URL should work for a file upload.

**Comment by benwilson512** [comment]
PR welcome.

**Comment by dfalling** [comment]
I dug into this a bit more and think AWS just changed their permissions.  I'm sending x-amz-acl in query params via this library, but was also adding it to headers in my UI.  If I remove it from the headers, it works.  Originally AWS didn't error over this, but it looks like it's redundant anyway.  Closing this out.
