### ISSUE TITLE
Cannot upload file to Google Cloud Storage bucket

### ISSUE THREAD

**Issue by yuntan** [ex-aws/ex_aws_s3#84]
### Environment
* Elixir v1.9.4
* ex_aws v2.1.0, ex_aws_s3 v2.0.1
* hackney v1.15.2

### Current behavior
When uploading file to GCS bucket, 400 returned. Code and returned request are shown below.

```elixir
upload.tempfile
|> ExAws.S3.Upload.stream_file
|> ExAws.S3.upload(bucket, s3_name, [
  {:content_type, upload.content_type},
])
|> ExAws.request
```

```
{:error, {:http_error, 400, %{body: "<?xml version='1.0' encoding='UTF-8'?><Error><Code>InvalidArgument</Code><Message>Invalid argument.</Message><Details>POST object expects Content-Type multipart/form-data</Details></Error>", headers: [{"X-GUploader-UploadID","XXX"}, {"Content-Type", "application/xml; charset=UTF-8"}, {"Content-Length", "188"}, {"Vary", "Origin"}, {"Date", "Mon, 20 Jan 2020 17:08:20 GMT"}, {"Server","UploadServer"}], status_code: 400}}}
```

### Expected behavior
Uploaded and 2xx returned.

**Comment by benwilson512** [comment]
Hi @yuntan, ExAws makes no promises at all about compatibility with non AWS services. You're of course welcome to look at the underlying API calls that `Upload` uses, and if there is a simple tweak we can do to make it also work with Google then I'd be happy to accept a PR.

**Comment by yuntan** [comment]
OK, I'll try. Thanks.

**Comment by zacksiri** [comment]
@yuntan anything you found to get this to work?
