### ISSUE TITLE
Uploading files broken in Elixir 1.10+

### ISSUE THREAD

**Issue by heimann** [ex-aws/ex_aws_s3#86]
### Environment

* Elixir & Erlang versions (elixir --version): Erlang/OTP 22, Elixir 1.10.2
* ExAws version `mix deps |grep ex_aws`: 2.0.2
* HTTP client version.  `hackney`: 1.15.2

### Current behavior
When trying to upload an image to S3 using elixir 1.10+ it breaks because of what seems like an error in the URL formatting that changed between 1.9 -> 1.10.

Uploading a file with `put_object/4` yields:
```
** (exit) an exception was raised:
    ** (ArgumentError) :path in URI must be nil or an absolute path if :host or :authority are given, got: %URI{authority: nil, fragment: nil, host: "s3.amazonaws.com", path: "XXXXX.png", port: 443, query: "", scheme: "https", userinfo: nil}
        (elixir 1.10.2) lib/uri.ex:662: String.Chars.URI.to_string/1
        (ex_aws 2.1.2) lib/ex_aws/request/url.ex:16: ExAws.Request.Url.build/2
        (ex_aws 2.1.2) lib/ex_aws/operation/s3.ex:29: ExAws.Operation.ExAws.Operation.S3.perform/2
...
```
### Expected behavior
In 1.9.4 the file uploads as expected.

**Comment by benwilson512** [comment]
Can you provide an example input that fails?

**Comment by heimann** [comment]
Ok now I feel like I'm crazy. I switched to 1.9.4 managed through `asdf` and uploading worked. Then I now switched back to give you an example file and all files work through 1.10.2. I'll just close this since I can't reproduce anymore :(

**Comment by benwilson512** [comment]
OK! Feel free to re-open if you run into a reproduceable example!

**Comment by opsb** [comment]
This appears to be a change in behaviour for elixir 1.10+ https://github.com/elixir-lang/elixir/issues/9588.

The solution is to make sure your s3 path is absolute (has a leading slash)

![image](https://user-images.githubusercontent.com/46232/92228106-9a115e00-eea7-11ea-8fd3-d7a1312530f0.png)

# Relative path
```
iex(1)> URI.to_string(%URI{authority: nil, fragment: nil, host: "s3.eu-west-1.amazonaws.com", path: "2020-09-04.csv", port: 443, query: "", scheme: "https", userinfo: nil})
** (ArgumentError) :path in URI must be nil or an absolute path if :host or :authority are given, got: %URI{authority: nil, fragment: nil, host: "s3.eu-west-1.amazonaws.com", path: "2020-09-04.csv", port: 443, query: "", scheme: "https", userinfo: nil}
    (elixir 1.10.2) lib/uri.ex:662: String.Chars.URI.to_string/1
```

# Absolute path
```
iex(1)> URI.to_string(%URI{authority: nil, fragment: nil, host: "s3.eu-west-1.amazonaws.com", path: "/2020-09-04.csv", port: 443, query: "", scheme: "https", userinfo: nil})
"https://s3.eu-west-1.amazonaws.com/2020-09-04.csv?"
iex(2)> 
```
