### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by ja-b** [ex-aws/ex_aws_s3#88]
Could we cut a new release with recent changes when possible?

Thanks Again

**Comment by jvoegele** [comment]
I too would really like to see a new release. I would like to be able to use the S3 transfer acceleration support that was added almost one year ago, but this has not been packaged for release yet.

**Comment by almirsarajcic** [comment]
Same as above. I want to use S3 Transfer Acceleration so currently I need to download `:ex_aws_s3` package from GitHub instead of Hex.pm.

**Comment by hidnasio** [comment]
Are there any plans to do a new release with the latest in master? Is there any way I can help? thanks

**Comment by bernardd** [comment]
Yep, just did it.
