### ISSUE TITLE
SignatureDoesNotMatch "Regression" with "marker" on Digital Ocean Spaces

### ISSUE THREAD

**Issue by jeffutter** [ex-aws/ex_aws_s3#90]
The following request worked great with `ex_aws` `1.15` but seems to be broken on `2.1.3/2.0.2`.

Note, I'm using Digital Ocean spaces. I can't speak to whether this works with AWS, but since it used to work with spaces hopefully we can get it working again.

### Environment

* Elixir & Erlang versions:
Erlang/OTP 22 [erts-10.7.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1]

Elixir 1.10.3 (compiled with Erlang/OTP 22)

* ExAws version:

ex_aws (Hex package) (mix)
locked at 2.1.3 (ex_aws) 0bdbe2ae
ex_aws_s3 (Hex package) (mix)
locked at 2.0.2 (ex_aws_s3) 0569f5b2

* HTTP client version:

hackney 1.16.0 (Hex package) (rebar3)
locked at 1.16.0 (hackney) 3bf0bebb

### Current behavior

```
> ExAws.S3.list_objects("my-bucket", marker: "Iceland 2017/_DSC3120.jpg") |> ExAws.request()
[debug] ExAws: Request URL: "https://sfo2.digitaloceanspaces.com/my-bucket/?marker=Iceland%2B2017%2F_DSC3120.jpg" HEADERS: [{"Authorization", "AWS4-HMAC-SHA256 Credential=XXXX/20200609/us-east-1/s3/aws4_request,SignedHeaders=host;x-amz-content-sha256;x-amz-date,Signature=fdec7497df0b8ad5b627585eabca09cb90edba71dda981b27bf12c55214af00f"}, {"host", "sfo2.digitaloceanspaces.com"}, {"x-amz-date", "20200609T123143Z"}, {"x-amz-content-sha256", "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"}] BODY: "" ATTEMPT: 1
{:error,
 {:http_error, 403,
  %{
    body: "<?xml version=\"1.0\" encoding=\"UTF-8\"?><Error><Code>SignatureDoesNotMatch</Code><RequestId>tx000000000000132977532-005edf8130-443fd0-sfo2a</RequestId><HostId>443fd0-sfo2a-sfo</HostId></Error>",
    headers: [
      {"Content-Length", "190"},
      {"x-amz-request-id", "tx000000000000132977532-005edf8130-443fd0-sfo2a"},
      {"Accept-Ranges", "bytes"},
      {"Content-Type", "application/xml"},
      {"Date", "Tue, 09 Jun 2020 12:31:44 GMT"},
      {"Strict-Transport-Security",
       "max-age=15552000; includeSubDomains; preload"}
    ],
    status_code: 403
  }}}

```

As you can see this worked OK on 1.15:

```
> ExAws.S3.list_objects("my-bucket", marker: "Iceland 2017/_DSC3120.jpg") |> ExAws.request()                                                                                                
[debug] Request URL: "https://sfo2.digitaloceanspaces.com/my-bucket/?marker=Iceland+2017%2F_DSC3120.jpg"                                                                                          
[debug] Request HEADERS: [{"Authorization", "AWS4-HMAC-SHA256 Credential=XXXX/20200609/us-east-1/s3/aws4_request,SignedHeaders=content-length;host;x-amz-content-sha256;x-amz-date,Signature
=57df96fd870c65f88b53f86873f689dbd8aa5c2078ea2e57f9990054b1c0d2c3"}, {"host", "sfo2.digitaloceanspaces.com"}, {"x-amz-date", "20200609T123318Z"}, {"content-length", 0}, {"x-amz-content-sha256", "e3b0c4429
8fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"}]                                                                                                                                                  
[debug] Request BODY: ""                                                                              
{:ok,                                                                                                 
 %{                                                                                                   
   body: %{.....
```

The only small difference I notice between the requests is how the URL is encoded in the debugging output `Iceland%2B2017` vs. `Iceland+2017`. However, that may be simply in the debug output.

I'm not sure where to look here to debug more, but any help is appreciated.

**Comment by jeffutter** [comment]
I'm wondering if it does have to do with the URL encoding. I tried passing a marker without a space in the name and it works on `2.1`

**Comment by benwilson512** [comment]
Can you reproduce this on AWS S3?

**Comment by jeffutter** [comment]
I can try later today. I don't really have a personal S3 account handy so it will probably take me a bit to get one setup.

One thing I did find that may be related though is: https://www.digitalocean.com/community/questions/receiving-403-from-spaces-when-accessing-private-file-containing-whitespace-using-aws-sdk

It sounds like this may be a slight incompatibility with the signing supported by DO Spaces.

**Comment by benwilson512** [comment]
@jeffutter ExAws suite explicitly targets AWS. There are zero compatibility guarantees with non S3 services. If you can reproduce on S3 please feel free to re-open. I'm also happy to take a PR that ensures that this works on both S3 and DO.

**Comment by kerryjj** [comment]
I think I've hit this as well, but directly to AWS. Just got the latest version from master and getting the same error when there's a space in the key name. It looks like the space gets converted/sanitised to + and the + then gets converted/sanitesed again to %2B. So instead of the Request URL containing %20 as expected by AWS it contains %2B instead.

I haven't quite found where this is happening yet. But I'll try to track it down and send a PR if I do.

**Comment by kerryjj** [comment]
This is actually an issue in ex_aws rather than ex_aws_s3. So I'll open a new issue with a PR in there that I think fixes it.
