### ISSUE TITLE
When the "putBucketversioning" function will be enabled?

### ISSUE THREAD

**Issue by pavo-tusker** [ex-aws/ex_aws_s3#92]
Hi,
We working on Bucket versioning. Right now in ExAWS S3, the "putBucketversioning" function is not enabled. Is there any possibility the function will be developed in the near future??

**Comment by benwilson512** [comment]
Hi @pavo-tusker you are welcome to open a PR, but `ex_aws_s3` is not under active development by any dedicated people at this time.
